#!/usr/bin/env bash
ip
bash ip
bash .local/bin/statusbar/ip 
ip route get 8.8.8.8
checkup
checkup
grep -r "/bin/bash" .*
grep -rl "/bin/bash" .*
grep --help
sb
grep -rn "/bin/bash" .*
grep -rn "/bin/bash" .*
cat /etc/systemd/system/numLockOnTty.service 
ls -al /usr/bin/numlockOnTty
systemctl status numlockOnTty
systemctl status /etc/systemd/system/numLockOnTty.service
systemctl start numLockOnTty
systemctl enable numLockOnTty
systemctl status numLockOnTty
systemctl status numlockOnTty
systemctl status numLockOnTty
ls -al /usr/bin/numlockOnTty
cat /etc/systemd/system/numLockOnTty.service 
systemctl status numLockOnTty 
cat /etc/systemd/system/numLockOnTty.service 
sudo nano /usr/bin/numlockOnTty
systemctl reload numLockOnTty
systemctl start numLockOnTty
systemctl status numLockOnTty 
p -S virtualbox
p -S virtualbox-guest-iso
cat /etc/fstab 
cat /etc/resolv.conf
su
grep -nir "Asus"
cd /
grep -nir "Asus" *
grep -nir "AsusTek" *
grep -nir "AsusTek" *
grep -nir "k10temp" *
grep -nir "asus" *
cd /
grep -nir "it8665" *
pwmconfig
sudo pwmconfig
su
inxi -Fxxxd
inxi -Fxxxd | grep "PRIME X370-PRO"
inxi -Fxxd | grep "PRIME X370-PRO"
inxi -Fxd | grep "PRIME X370-PRO"
inxi -Fx | grep "PRIME X370-PRO"
inxi -F | grep "PRIME X370-PRO"
inxi -F
inxi
cat  /etc/makepkg.conf
cat  /etc/makepkg.conf | grep MAKEFLAGS
gpasswd -a $name power
gpasswd -a yiannis power
su
pacman -Qq | grep gtk
pacman -Qi gtk2
pacman -Qi gcolor3
pacman -Si gcolor
pacman -Si gcolor2
pacman -S gcolor
sudo pacman -S gcolor
sudo pacman -Ss gcolor
sudo pacman -Ss gcolor
cd anergos/
ga -A
gs
gc "merge"
git push
git push
dot add .local/bin/
dot add .bashrc
dot add .bash_profile
dots
dotc " /bin/env . "
dot push
dot push --set-upstream origin master
mkdir msb
lsblk
sudo mount /dev/sda2 msb
cd msb/
cd -r EFI/Microsoft /boot/EFI/
cd -R EFI/Microsoft /boot/EFI/
cp -r EFI/Microsoft /boot/EFI/
sudo cp -r EFI/Microsoft /boot/EFI/
efibootmgr
sudo efibootmgr -n 0001
reboot
reboot
pacman -Ss xback
p -S xorg-xbacklight
xbacklight --help
xbacklight -set 50
p -Ss light
yay brightnessctl
brightnessctl --list
brightnessctl -d input2::numlock s 1
sudo brightnessctl -d input2::numlock s 0
sudo brightnessctl -d input2::numlock s 1
sudo brightnessctl -d input2::numlock s 1
cp /etc/pacman.d/mirrorlist.pacnew /etc/pacman.d/mirrorlist
sudo \cp /etc/pacman.d/mirrorlist.pacnew /etc/pacman.d/mirrorlist
sudo cp /etc/pacman.d/mirrorlist.pacnew /etc/pacman.d/mirrorlist
diff /etc/pacman.d/mirrorlist.pacnew /etc/pacman.d/mirrorlist
efibootmgr 
sudo efibootmgr -n 0001
reboot
sudo efibootmgr -n 0001
reboot
ps -Syy
ssb /etc/pacman.d/mirrorlist
p -Syy
p -S gnome-terminal
gnome-terminal 
dbus-launch gnome-terminal
echo $DBUS_SESSION_BUS_ADDRESS
cat /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
ls -al /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
sb .xinitrc 
ls
dconf-editor
dconf --help
dconf read
p -Qq | grep ttf
fc-list
fc-list | grep source
ls
p --help
p -F --help
p -Fo /usr/share/fonts/adobe-source-code-pro/
p -Fyo /usr/share/fonts/adobe-source-code-pro
p -Fo /usr/share/fonts/adobe-source-code-pro
p -Fo /usr/share/fonts/adobe-source-code-pro/SourceCodePro-Regular.otf 
p -Qq
p -Qq | grep totem\
p -Qq | grep tilix
p -Qq | grep orca
p -Qq | grep notify-osd
p -Qq | grep nemiver
p -Qq | grep mutter
p -Qq | grep mousetweaks
p -Qq | grep moserial
p -Qq | grep meld
p -Qq | grep gthumb
p -Qq | grep glib-net
p -Qq | grep gimp
p -Qq | grep libsoup
export TERMINAL="gnome-terminal"
p -Rns termite
ps
pc
yay -S xkb-switch
p -S pcmanf,
p -S pcmanfm
p -Qq |grep gtk
sudo pacman -S flatpak
gnome-terminal --help
export TERMINAL="gnome-terminal"
p -Rns termite
ps
pc
yay -S xkb-switch
p -S pcmanf,
p -S pcmanfm
p -Qq |grep gtk
sudo pacman -S flatpak
gnome-terminal --help
hostnamectl 
hostname
[[ hostname == killua ]] && echo ok
[[ hostname = killua ]] && echo ok
[[ hostname = "killua" ]] && echo ok
[[ $(hostname) = "killua" ]] && echo ok
[ $(hostname) = "killua" ] && echo ok
dot add .config/i3 .config/sway/
dot add .xinitrc
dot add .local/bin/i3confmerge
dot add .config/sublime-text-3/Packages/User/i3wm_config.sublime-settings
dot diff .config/pcmanfm/default/pcmanfm.conf
dot diff .config/libfm/libfm.conf
dot add .config/libfm/libfm.conf
dot add .bash_profile
dotc "termite --> gnome-terminal"
dot push
cd anergos/
dot add programs/
git add programs/
gitc "gnome-terminal"
gc "gnome-terminal"
git push
dot checkout
dot restore --staged programs/
dots
gs
sb .config/i3blocks/config 
xprop
gnome-teminal -e "echo ok"
gnome-temrinal -e "echo ok"
gnome-terminal -e "echo ok"
gnome-terminal --help
gnome-terminal 
 $TERMINAL --termname dropdown
man gnome-terminal
gnome-terminal --execute popupgrade
gnome-terminal --execute--  popupgrade
gnome-terminal --execute --  popupgrade
gnome-terminal popupgrade
gnome-terminal && popupgrade
ping -q -w 1 -c 1 `ip r | grep -m 1 default | cut -d ' ' -f 3`
ip r | grep -m 1 default | cut -d ' ' -f 3
checkup
gnome-terminal && popupgrade
sb .config/i3blocks/config 
checkup
cat /tmp/available_updates 
newpc
gnome-terminal --title="dropdown"
gnome-terminal --hide-menubar --title="dropdownGT"
xprop
newpc
gnome-terminal --title="dropdown"
gnome-terminal --hide-menubar --title="dropdownGT"
xprop
checkup
efibootmgr
efibootmgr -n 0001
sudo efibootmgr -n 0001
dot add .config/i3 .config/sway
dot add .local/bin/
dot add .config/i3blocks/
dots
dotc "fed"
dot push
cd anergos/
git add programs/
gs
gc "term"
git push
reboot
ps
ps -aux | grep pac
ps -aux | grep chec
sb .config/i3blocks/
colors
sudo efibootmgr -n 0001
reboot
echo $TERM
echo $TERMINAL 
$TERMINAL --title="dropdownGT" --hide-menubar
cat /usr/share/doc/pulsemixer/README.md
p -S python-pip
p -Rns pulsemixer
pip install pulsemixer
pip install --user pulsemixer
xprop
px
pc
p -S pavcontrol
p -S pauvcontrol
p -S pavucontrol
pavucontrol 
xprop
pip --help
pip uninstall --user pulsemixer
pip uninstall pulsemixer
pip uninstall --user pulsemixer
pip uninstall pulsemixer
dot add .local/bin/pulsemixer
dots
sudo systemctl status dhcpcd
$TERMINAL --title="dropdownGT" --hide-menubar
$TERMINAL --title="dropdownGT" --hide-menubar
p -S i3
p -S i3status
p -Rns pip
p -Rns python-pip
pc
newpc
newpc 
ls -al .local/bin
ll
la
ls
ls -1
pc
yay piper
piper 
checkup 
sudo systemctl status dhcpcd
pulsemixer 
dots
cat /etc/sysctl.d/99-sysctl.conf
sudo rm /etc/sysctl.d/99-sysctl.conf
cat /etc/sysctl.d/99-sysctl.conf
sudo rm /etc/sysctl.d/99-sysctl.conf
p -S i3
p -S i3status
i3status 
newpc 
wc -l < .local/Fresh_pack_list 
wc -l < .local/Fresh_pack_list && pc
(( $(wc -l < .local/Fresh_pack_list) - $(pc) ))
( $(wc -l < .local/Fresh_pack_list) - $(pc) )
expr $(wc -l < .local/Fresh_pack_list) - $(pc)
expr $(pc) - $(wc -l < .local/Fresh_pack_list)
sb .local/bin/newpc 
pc
alias pc
newpc
sb .local/bin/newpc 
newpc
test subl3
time suble3
time subl3
p -S flatpack
p -S flatpak
zenmap --help
pacman -Fo $(which zenmap)
flatpak search sublime
flatpak install flathub com.sublimetext.three
time subl3
time subl3 | awk '{print $3}'
time subl3 | awk '{print $2}'
time subl3
time subl3 | awk '{print $3}'
time subl3 | awk '{print $2}'
dot add .local/bin
dot add .config/sway .config/i3
dot diff .config/sublime-text-3/Packages/User/i3wm_config.sublime-settings
dot add .config/sublime-text-3/Packages/User/i3wm_config.sublime-settings
dots
dotc "D"
dot push
echo "UUID=fe8b7dcf-3bae-4441-a4f3-a3111fee8ca4  /media/Data    ext4 rw,noatime,nofail,user,auto    0  2"
echo "# /dev/sda1 LABEL=data" && echo "UUID=fe8b7dcf-3bae-4441-a4f3-a3111fee8ca4  /media/Data    ext4 rw,noatime,nofail,user,auto    0  2"
cat > /etc/sudoers.d/wheel <<-EOF
%wheel ALL=(ALL) ALL
%wheel ALL=(ALL) NOPASSWD: /usr/bin/wifi-menu,/usr/bin/mount,/usr/bin/umount,/usr/bin/loadkeys,/usr/bin/systemctl restart systemd-networkd,/usr/bin/systemctl restart systemd-resolved,/usr/bin/systemctl restart NetworkManager

cat > /etc/sudoers.d/wheel <<-EOF
%wheel ALL=(ALL) ALL
%wheel ALL=(ALL) NOPASSWD: /usr/bin/wifi-menu,/usr/bin/mount,/usr/bin/umount,/usr/bin/loadkeys,/usr/bin/systemctl restart systemd-networkd,/usr/bin/systemctl restart systemd-resolved,/usr/bin/systemctl restart NetworkManager
ln .config/sublime-text-3/ .var/app/com.sublimetext.three/config/
ln -S .config/sublime-text-3/ .var/app/com.sublimetext.three/config/
ln -s .config/sublime-text-3/ .var/app/com.sublimetext.three/config/
ln -s .config/sublime-text-3 .var/app/com.sublimetext.three/config/
ln -s ~/.config/sublime-text-3 ~/.var/app/com.sublimetext.three/config/
flatpak install flathub com.sublimetext.three
flathub com.sublimetext.three
com.sublimetext.three
dots
dot restore .config/sublime-text-3
dot add .var/app/com.sublimetext.three/config/sublime-text-3
flatpak run com.sublimetext.three
flatpak run com.sublimetext.three
dot diff .config/sublime-text-3/Packages/User/Package Control.last-run
dot diff .config/sublime-text-3/Packages/User/Package\ Control.last-run
dot add .config/sublime-text-3/Packages/User/Package\ Control.last-run
dots
dots
sort test.sh 
rm test.sh 
cat subletest 
rm subletest 
ls -al
cat .bashrc 
ll
dots
flatpak remote-ls flathub | grep org.gtk.Gtk3theme
echo "flatpak remote-ls flathub | grep org.gtk.Gtk3theme " > flatnotes
echo "#\!/bin/bash" > flatnotes
echo "flatpak remote-ls flathub | grep org.gtk.Gtk3theme " >> flatnotes
cat flatnotes 
alias sb
sb .config/bash/aliasrc 
sb flatnotes 
sudo pacman -Syu
sudo pacman -Ss lxappearance
sudo pacman -S lxappearance-gtk3
sudo pacman -Ss breeze
sudo pacman -S breeze-gtk
sudo pacman -Ss material
sudo pacman -Rns
yay Adwaita-dark
flatpak remote-ls flathub | grep org.gtk.Gtk3theme
flatpak remote-ls flathub | grep org.gtk.Gtk3theme >> flatnotes 
sudo pacman -Rns subl3
sudo pacman -Rns sublime-text-dev
htop
flatpak install --help
command -v pip
command -v flatpak
command -v flatpak
cd a
cd anergos/
ga -A
gs
sudo efibootmgr -n 0001
sudo rm /etc/sysctl.d/99-sysctl.conf
time "flatpak run com.sublimetext.three"
time flatpak run com.sublimetext.three
time (flatpak run com.sublimetext.three)
time (flatpak run com.sublimetext.three &)
time subl3
pkill subl3
flatpak run com.sublimetext.three
cat flatnotes 
flatpak remote-ls flathub | grep org.gtk.Gtk3theme
flatpak install flathub org.gtk.Gtk3theme.Breeze-Dark
flatpak install flathub --noninteractive org.gtk.Gtk3theme.Breeze-Dark
flatpak list installed
flatpak list --installed
flatpak list -
flatpak list --help
flatpak list
sb anergos/
alias sb
cat .config/bash/aliasrc 
sb
sb anergos/
ll
starwars
flatpak run com.sublimetext.three & ; disown
flatpak run com.sublimetext.three &; disown
flatpak run com.sublimetext.three & disown
sb anergos/
sb .config/bash/aliasrc 
flatpak run com.sublimetext.three & disown
sb am
sb anergos
flatpak run com.sublimetext.three & disown
ps
htop
cd anergos/
gs
gitc "things.."
gc "things.."
git push
sudo pacman -S nautilus
grep ==help
grep --help
sb
sb .config/i3
grep --help
yay -S sublime-text-dev
flatpak list --installed
flatpak list installed
flatpak list 
flatpak uninstall com.sublimetext.three org.freedesktop.Platform.html5-codecs org.freedesktop.Sdk org.gtk.Gtk3theme.Breeze-Dark
subl3 .config/bash/aliasrc 
sb
sudo pacman -Rns flatpak
pc
ls
ls
dot rm .var/app/com.sublimetext.three/config/sublime-text-3
dots
ls /usr/bin/virtualbox
ll /usr/bin/virtualbox
lspci | grep VirtualBox
[[ $(lspci | grep VirtualBox) ]] || echo ok
[[ $(lspci | grep VirtualBox) ]] && [ -f /usr/bin/pacman ] || echo ok
sudo pacman -Rns flatpak
ls
ls
dot rm .var/app/com.sublimetext.three/config/sublime-text-3
dots
sb anergos/
sudo pacman -Rns piper
sudo pacman -Rns  lxappearance-gtk3
p -Rns  lxappearance-gtk3
yay -Rns adwaita-dark
newpc
pc
sudo pacman -S i3
virtualbox
yay -Rns brightnessctl
sudo pacman -Rns $(pacman -Qqdt)
pacman -Q --help
