#!/bin/sh

alias \
    free="free --mebi"\
	cp="cp --interactive"\
	df="df --human-readable"\
	diff="diff --color=auto"\
	dotc="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME commit -m"\
	dots="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME status"\
	dot="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"\
	egrep="egrep --colour=auto"\
	fgrep="fgrep --colour=auto"\
	ga="git add -A"\
	gc="git commit -m"\
	grep="grep --colour=auto"\
	gs="git status"\
	hcat="highlight --out-format=ansi"\
	hcatt="highlight --src-lang"\
	ll='ls --color=auto -alF'\
	ls="ls --literal --human-readable --color=auto --group-directories-first "\
	mkd="mkdir -pv"\
	pc="pacman -Qq | wc -l"\
	printascii="man ascii | grep -m 1 -A 63 --color=never Oct"\
	starwars="telnet towel.blinkenlights.nl"\
	yt="youtube-dl --add-metadata"\
	inxi="inxi -FxxxzD"


[[ `command -v lsd` ]] && alias \
	ll="lsd --human-readable --color=auto -al"\
	ls="lsd --human-readable --color=auto "

# Neovim || Flatpak Neovim
alias \
	nvim="nvim || flatpak run io.neovim.nvim" \
	nvimd="nvim -d || flatpak run io.neovim.nvim -d"

flatpak_theme() {
	for package in $(ls "$HOME/.var/app/"); do
		[ -d "$HOME/.var/app/$package/config/gtk-3.0" ] ||
		/usr/bin/ln -s "$HOME/.config/gtk-3.0" "$HOME/.var/app/$package/config/"
	done
}

# For Raspberry Pi 
[[ `command -v /opt/vc/bin/vcgencmd` ]] && alias \
    temp="/opt/vc/bin/vcgencmd measure_temp"