#!/bin/bash

alias \
    free="free --mebi"\
	cp="cp --interactive"\
	df="df --human-readable"\
	diff="diff --color=auto"\
	egrep="egrep --colour=auto"\
	fgrep="fgrep --colour=auto"\
	g="git"\
	grep="grep --colour=auto"\
	hcat="highlight --out-format=ansi"\
	ll='ls --color=auto -alF'\
	ls="ls --literal --human-readable --color=auto --group-directories-first "\
	inxi="inxi -FxxxzD"\
	stime="/usr/bin/time -f 'Spacetime: %MK %E'"

# Dotfiles managment
[[ -d "$HOME/.cfg" ]] && alias \
	dot="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"\

[[ `command -v exa` ]] && alias \
	ll="exa --icons -al"\
	ls="exa --icons"

# For Raspberry Pi 
[[ `command -v /opt/vc/bin/vcgencmd` ]] && alias \
    temp="/opt/vc/bin/vcgencmd measure_temp"

# Start Virtual camera for OBS
alias virt-cam="sudo modprobe v4l2loopback devices=1 card_label="OBS Cam" exclusive_caps=1"
